// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://uvdbnwxppmudgsjkdqza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2ZGJud3hwcG11ZGdzamtkcXphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NzA3NDUsImV4cCI6MjA2ODI0Njc0NX0.Pj540GiApm1uVSE59WW9y8pnYM503G5HZUdyEY72mLs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);